services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211
         - PLAYERS=16 # Número de vagas do servidor
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC-3
         - COMMUNITY=true  # Mostra o seu servidor na listagem da comunidade.
         - SERVER_NAME="Nome do servidor"
         - SERVER_DESCRIPTION="Descrição do servidor"
         - SERVER_PASSWORD="" # Senha do servidor.
         - ADMIN_PASSWORD="admin" # Senha do administrador.
         - DISCORD_WEBHOOK_URL="" # Insira a sua webhook do discord, algo tipo: https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      volumes:
         - ./servidor:/palworld/
